version: '3'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis
    ports:
      - 6379:6379
  # identity:
  #   build: 
  #     context: .
  #     dockerfile: ./build/docker/dockerfile
  #   ports:
  #     - 12568:12568
